version: '3.0'

expectations:
  population_size: 1000

actions:

  # Generate ethnicity study population
  generate_study_population_ethnicity:
    run: > 
      cohortextractor:latest generate_cohort 
      --study-definition study_definition_ethnicity 
      --output-dir=output
      --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/input_ethnicity.csv
  
  generate_study_population_bp002_1y_lookback:
    run: > 
      cohortextractor:latest generate_cohort 
      --study-definition study_definition_bp002_1y_lookback
      --index-date-range "2019-04-01 to 2023-03-31 by month" 
      --output-dir=output
      --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/input_bp002_1y*.csv
  
  generate_study_population_bp002_5y_lookback:
    run: > 
      cohortextractor:latest generate_cohort 
      --study-definition study_definition_bp002_5y_lookback 
      --index-date-range "2019-04-01 to 2023-03-31 by month" 
      --output-dir=output
      --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/input_bp002_5y*.csv
  
  join_ethnicity:
    run: >
      cohort-joiner:v0.0.12 
        --lhs output/input_bp002*.csv
        --rhs output/input_ethnicity.csv
        --output-dir output/joined
    needs: [generate_study_population_ethnicity, generate_study_population_bp002_1y_lookback, generate_study_population_bp002_5y_lookback]
    outputs:
      highly_sensitive:
        cohort: output/joined/input_bp002*.csv

  generate_measures_bp002_1y_lookback:
     run: >
       cohortextractor:latest generate_measures 
       --study-definition study_definition_bp002_1y_lookback 
       --output-dir=output/joined
     needs: [join_ethnicity]
     outputs:
       moderately_sensitive:
         measure_csv: output/joined/measure_bp002_1y*_rate.csv

  generate_measures_bp002_5y_lookback:
     run: >
       cohortextractor:latest generate_measures 
       --study-definition study_definition_bp002_5y_lookback 
       --output-dir=output/joined
     needs: [join_ethnicity]
     outputs:
       moderately_sensitive:
         measure_csv: output/joined/measure_bp002_5y*_rate.csv

  generate_deciles_charts:
    run: >
      deciles-charts:v0.0.15
        --input-files output/joined/measure_*.csv
        --output-dir output/joined/
    config:
      show_outer_percentiles: false
      tables:
        output: true
      charts:
        output: true
    needs: [generate_measures_bp002_1y_lookback, generate_measures_bp002_5y_lookback]
    outputs:
      moderately_sensitive:
        deciles_charts: output/joined/deciles_chart_*_*_practice_breakdown_rate.png
        deciles_tables: output/joined/deciles_table_*_*_practice_breakdown_rate.csv
      
  join_measures:
    run: r:latest analysis/join_measures.R
    needs: [generate_measures_bp002_1y_lookback, generate_measures_bp002_5y_lookback]
    outputs:
      moderately_sensitive:
        bp002_achievement_csv: output/joined/measures/measures_bp002_achievem.csv
